version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - zachferland
  assignees:
  - zachferland
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.839.0
    - 2.843.0
    - 2.848.0
    - 2.853.0
    - 2.858.0
    - 2.863.0
    - 2.868.0
    - 2.874.0
    - 2.879.0
    - 2.884.0
  - dependency-name: redis
    versions:
    - 3.0.2
    - 3.1.0
  - dependency-name: did-resolver
    versions:
    - 2.1.2
    - 2.2.0
    - 3.0.1
    - 3.0.2
  - dependency-name: ipfs
    versions:
    - 0.53.2
    - 0.54.1
    - 0.54.2
  - dependency-name: ipfs-http-client
    versions:
    - 48.2.2
    - 49.0.1
    - 49.0.2
  - dependency-name: multihashes
    versions:
    - 3.1.1
    - 3.1.2
